# Generated by Django 2.1.3 on 2018-12-31 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkoutType',
            new_name='Workouts',
        ),
        migrations.RenameField(
            model_name='workouts',
            old_name='workout_name',
            new_name='workout_title',
        ),
    ]
