# Generated by Django 2.1.3 on 2019-01-31 14:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treps', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999)], verbose_name='target reps')),
                ('tsets', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='target sets')),
                ('tweight', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='target weight')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Workouts', verbose_name='exercise type')),
            ],
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ex', to='tracker.Exercise')),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='compName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp', to='tracker.Competition'),
        ),
        migrations.AddField(
            model_name='entry',
            name='routName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rout', to='tracker.Routine'),
        ),
    ]
