# Generated by Django 2.1 on 2019-01-03 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_remove_workouts_workout_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='workouts',
            name='workout_url',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
