# Generated by Django 2.1.3 on 2018-11-15 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20181114_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='sets',
            field=models.IntegerField(),
        ),
    ]
