# Generated by Django 2.1.3 on 2018-12-31 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20181231_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='workout_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.Workouts'),
        ),
    ]
