# Generated by Django 2.1.3 on 2019-01-03 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_workouts_workout_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='workout_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='tracker.Workouts'),
        ),
    ]
