# Generated by Django 2.1.3 on 2019-01-03 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20181231_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='workouts',
            name='workout_url',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
