# Generated by Django 2.1.3 on 2019-01-03 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20190103_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workouts',
            name='workout_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
