# Generated by Django 2.1.3 on 2019-01-31 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20190131_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routine',
            name='exercise',
        ),
        migrations.AddField(
            model_name='routine',
            name='exercise',
            field=models.ManyToManyField(related_name='ex', to='tracker.Exercise'),
        ),
    ]
