# Generated by Django 2.1.3 on 2019-01-08 02:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20190103_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompeEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalReps', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compName', models.CharField(max_length=100)),
                ('startDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('endDate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compeentry',
            name='compName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Competition'),
        ),
        migrations.AddField(
            model_name='compeentry',
            name='workout_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Workouts'),
        ),
        migrations.AddField(
            model_name='entry',
            name='compName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.Competition'),
        ),
    ]
