# Generated by Django 2.1.3 on 2019-01-08 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20190107_2101'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompeEntry',
            new_name='CompEntry',
        ),
    ]
