# Generated by Django 2.1.3 on 2019-01-09 00:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_auto_20190107_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compentry',
            name='compName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition', to='tracker.Competition'),
        ),
        migrations.AlterField(
            model_name='compentry',
            name='totalReps',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(999999)]),
        ),
        migrations.AlterField(
            model_name='competition',
            name='compName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='entry',
            name='reps',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999)]),
        ),
        migrations.AlterField(
            model_name='entry',
            name='sets',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='entry',
            name='weight',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
