# Generated by Django 2.1.5 on 2019-02-06 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_compmember'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compmember',
            old_name='compMember',
            new_name='user',
        ),
    ]
